name: Eight Workflow 

on: 
    workflow_dispatch:
        inputs:
            titleCustom:
                description: Type the Title 
                type: string
                required: true
                default: 'Hello World'
                
      
   
jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        steps:
            - name: Event Vars 
              run: |
                echo $GITHUB_SHA
                echo $GITHUB_REF
