name: First Workflow 

on: [push]

jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        steps:
            - name: Display some Text 
              run: echo "Some Text" 
            - name: Command in Miltiline 
              run: |
                node -v
                npm -v 