name: Nineth Workflow 

on: 
    repository_dispatch:
        types: [test]


jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        steps:
            - name: Event Vars 
              run: |
                echo "Title: ${{github.event.client_payload.titleTest}}"