name: Ten Workflow 

on: push
run-name: 'Display Context Info'

jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        steps:
            - name: Contexts and Expressions 
              id: context 
              run: |
                echo '${{toJson(github)}}'
                echo '${{toJson(runner)}}'
                echo '${{toJson(job)}}'
                echo '${{toJson(steps)}}'
            - name: Show Steps Context
              run: |
                echo '${{ toJson(steps)}}'
                