name : Thriteenth Workflow

on: push 

jobs:
    #failure() success() always() cancelled()
    job: 
        runs-on: ubuntu-latest
        steps:
          - name: Failure Step
            id: error-step
            run: exit 1     
          - name: Runs on Cancelled 
            if: ${{cancelled()}}
            run: echo 'Runs on Cancelled'
          - name: Runs on any case 
            if: ${{always()}}
            run: echo 'Runs on any case'
          - name: Runs on any Success 
            if: ${{success()}}
            run: echo 'uns on any Success'
          - name: Runs on any Failure 
            if: ${{failure() && steps.error-step.conclusion == 'failure'}}
            run: echo 'Runs on any Failure' # на предыдущем ошибка если          
    second-job:
        runs-on: ubuntu-latest
        needs: job #ждет заврешние предыдущего 
        if: ${{failure()}}
        steps:
            - run : echo 'Job was failed'
             