name: Thrid Workflow 

on: push # event 

jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        steps:
            - name: List Files
              run: lsfsa -a
            #- uses: actions/checkout@v4  # Этот шаг использует GitHub Actions для клонирования репозитория
            - name: Copy Files
              run: |
                git init 
                git remote add origin https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
                git fetch origin 
                git checkout main 
              
            - name: List Files
              run: ls -a