name: Twelve Workflow 

on: [push]



jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        environment: "production"
        steps:          
            - name: Our Vars & Secrets 
              run: |
                echo '${{vars.STATUS}}'
                echo '${{secrets.PASSWORD}}'

