name: Twelve Workflow 

on: [push]



jobs:
    run-first-command: #name
        runs-on: ubuntu-latest #os 
        environment: "staging" # без него будет вывод секретов. Тут зависит от приоритетов
        steps:          
            - name: Our Vars & Secrets 
              run: |
                echo '${{vars.STATUS}}'
                echo '${{secrets.PASSWORD}}'

